In [1]:
import numpy as np

In [4]:
A = np.array([[4, -3, 1], [2, 1, 3], [-1, 2, -5]], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print('Matrix A:') 
print(f'{A}')
print('\n')
print(f'Vector b:') 
print(f'{b}')

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]


Vector b:
[-10.   0.  17.]


In [5]:
A.shape

(3, 3)

In [6]:
b.shape

(3,)

Now use np.linalg.solve(A, b) function to find the solution of the system  (1)
 . The result will be saved in the 1-D array  𝑥
 . The elements will correspond to the values of  𝑥1
 ,  𝑥2
  and  𝑥3
 :

In [7]:
x = np.linalg.solve(A, b)
print(f'Solution: {x}')

Solution: [ 1.  4. -2.]


### Evaluating the determinant of a matrix

In [9]:
d = np.linalg.det(A)

print(f'The determinant of A is: {d:.2f}')

The determinant of A is: -60.00


### What happens when the system has no unique solution?

In [10]:
A_2 = np.array([[1, 1, 1], [0, 1, -3], [2, 1, 5]], dtype=np.dtype(float))

b_2 = np.array([2, 1, 0], dtype=np.dtype(float))

print(np.linalg.solve(A_2, b_2))

LinAlgError: Singular matrix

In [11]:
d_2 = np.linalg.det(A_2)

print(f'The determinant of A_2 is: {d_2}')

The determinant of A_2 is: 0.0
