In [1]:
import numpy as np

In [2]:
def swap_rows(M, row_index_1:int, row_index_2:int):
    
    """
    Swap rows in a given matrix

    Parameters:
        - M: matrix (numpy.array), The input matrix to perform row operations (swaps) on
        - row_index_1 (int): The index of the first row to be swapped
        - row_index_2 (int): The index of the second row to be swapped
    """

    # copy matrix M so the changes do not affect the original matrix.
    M = M.copy()

    # swap indexes
    M[[row_index_1, row_index_2]] = M[[row_index_2, row_index_1]]

    return M
    

In [3]:
M = np.array([[1, 3, 6], [0, -5, 2], [-4, 5, 8]])

print(M)

[[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]


In [4]:
M_swapped = swap_rows(M, 0, 2)
print(M_swapped)

[[-4  5  8]
 [ 0 -5  2]
 [ 1  3  6]]


Getting the index of the first non zero value in a column starting from a specified value

In [5]:
def get_index_first_non_zero_value_from_column(M, column, starting_row):
    """
    Retrieve the index of the first non-zero value in a specified column of the given matrix
    
    Parameters: 
        -matrix (numpy.array): The input matrix to search for non-zero values.
        -column (int): The index of the column to search.
        -starting_row (int): The starting row index for the search.

    Returns:
        int: The index of the first non-zero value in the specified column, starting form the given row.
        Returns -1 if the non-zero value is found
    """
    
    #Get the column array starting from the specified row:
    column_array = M[starting_row:, column]
    for i, val in enumerate(column_array):
        # Iterate over every value in the column array.
        # To check for non-zero values, you must always use np.isclose instead of doing 'val == 0'
        if not np.isclose(val, 0, atol = 1e-5):
            # If one non-zero value is found, then adjust the index to match the correct index and return it.
            index = i + starting_row
            return index
        
    # If no non-zero value is found below it, return -1
    return -1

In [6]:
N = np.array([[0,5,-3,6,8], [0,6,3,8,1], [0,0,0,0,0], [0,0,0,0,7], [0,2,1,0,4]])
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [7]:
print(get_index_first_non_zero_value_from_column(N, 0, 0))

-1


In [8]:
print(get_index_first_non_zero_value_from_column(N, -1, 2))

3


### Finding the first non-zero element for any row

In [9]:
def get_index_first_non_zero_value_from_row(M, row, augmented = False):
    """
    Find the index of the first non-zero value in the specified row

    Parameters:
     - matrix (numpy.array): The input matrix to search for non-zero values
     - row (int): The index of the row to search
     - augmented (bool): Pass this True if you are dealing with an augmented matrix,
                        so it will ignore the constant values (the last column in the augmented matrix)
        
    Returns:
        int: The index of the first non-zero value in the specified row.
        Returns -1 if the first non-zero value is found.
    """

    # Create a copy to avoid modofying the original matrix
    M = M.copy()

    # If it is an augmented matrix, then ignore the constant values
    if augmented == True:
        # Isolating the coefficient matrix (removing the constant terms)
        M = M[:,:-1]
    
    # Get the desired row
    row_array = M[row]
    for i, val in enumerate(row_array):
        # If finds a non-zero value, returs the index. Otherwise, returns -1.
        if not np.isclose(val, 0, atol = 1e-5):
            return i
    return -1



In [10]:
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [11]:
print(f'Output for row 2: {get_index_first_non_zero_value_from_row(N, 2)}')
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3)}')

Output for row 2: -1
Output for row 3: 4


Now lets pass the argument augmented = True. This will make the algorithm consider N an augmented matrix, therefore the last column would be removed from consideration.

In [12]:
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3, augmented = True)}')

Output for row 3: -1


### Constructing the augmented matrix

In [13]:
def augmented_matrix(A, B):
    """
    Create an augmented matrix by horizontally stacking two matrices A and B.

    Parameters:
    - A (numpy.array): First matrix.
    - B (numpy.array): Second matrix.

    Returns:
    - numpy.array: Augmented matrix obtained by horizontally stacking A and B.
    """
    augmented_M = np.hstack((A,B))
    return augmented_M

In [14]:
A = np.array([[1,2,3], [3,4,5], [4,5,6]])
B = np.array([[1], [5], [7]])

print(augmented_matrix(A,B))

[[1 2 3 1]
 [3 4 5 5]
 [4 5 6 7]]


### Solving the row-echelon form in a matrix

In [24]:
def row_echelon_form(A, B):
    """
    Utilizes elementary row operations to transform a given set of matrices,
    which represent the coefficients and constant terms of a linear system, into row echelon form.

    Parameters:
        - A (numpy.array): The input square matrix of coefficients.
        - B (numpy.array): The input column matrix of constant terms.

    Returns:
        numpy.array: A new augmented matrix in row echelon form with pivots as 1.
    """
    # Before any computation, check if matrix A (coefficient matrix) has non-zero detreminant.
    # It will use the numpy sub library np.linalg to compute it.

    det_A = np.linalg.det(A)

    # Returns "Singular System" if determinant is zero
    if np.isclose(det_A, 0) == True:
        return 'Singular System'
    
    # Make copies of the input matrices to avoid modifying the originals
    A = A.copy()
    B = B.copy()

    # Convert the matrices to float to prevent integer division
    A = A.astype('float64')
    B = B.astype('float64')

    # Number of rows in the coefficient matrix
    num_rows = len(A)


    # Transform the matrices A and B into the augmented matrix M
    M = augmented_matrix(A, B) # The function is given in a different cell above

    # Iterate over the rows
    for row in range(num_rows):

        # The first pivot candidate is always on the main diagonal
        pivot_candidate = M[row,row]

        # Check if the pivot candidate is zero
        if np.isclose(pivot_candidate, 0) == True:
            # Get the index of the first non-zero value below the pivot element
            first_non_zero_value_below_pivot_element = get_index_first_non_zero_value_from_column(M, row, row)

            # Swap rows
            M = swap_rows(M, row, first_non_zero_value_below_pivot_element)

            # Get the pivot which is in the main diagonal now
            pivot = M[row, row]

        # If pivot_candidate is already non-zero, then it is the pivot for this row
        else:
            pivot = pivot_candidate

        # Time to perform the row reduction
        # Divide the current row bu the pivot, so that the new pivot will be 1
        # Using the formula current_row -> 1/pivot * current_row
        # Where the current row can be accessed using M[row]
        M[row] = 1/pivot * M[row]

        # Perform row reduction for rows below the current row
        for j in range(row + 1, num_rows):
            value_below_pivot = M[j,row]

            # Perform row reduction using the formular
            # row_to_reduce -> row_to_reduce - value_below_pivot * pivot_row
            M[j] = M[j] - value_below_pivot * M[row]


    return M

In [25]:
A = np.array([[2,-1,1], [2,2,4], [4,1,0]])
B = np.array([[1], [2], [-1]])

row_echelon_form(A, B)

array([[ 1.        , -0.5       ,  0.5       ,  0.5       ],
       [ 0.        ,  1.        ,  1.        ,  0.33333333],
       [-0.        , -0.        ,  1.        ,  0.8       ]])

Performing back substitution

In [26]:
def back_substitution(M):
    """
    Perform back substitution on an augmented matrix (with unique solution) in reduced row echelon form to find the solution to the linear system.

    Parameters:
    - M (numpy.array): The augmented matrix in row echelon form with unitary pivots (n x n+1).

    Returns:
    numpy.array: The solution vector of the linear system.
    """
    
    # Make a copy of the input matrix to avoid modifying the original
    M = M.copy()

    # Get the number of rows (and columns) in the matrix of coefficients
    num_rows = M.shape[0]

    ### START CODE HERE ####
    
    # Iterate from bottom to top
    for row in reversed(range(num_rows)): 
        substitution_row = M[row,:]

        # Get the index of the first non-zero element in the substitution row. Remember to pass the correct value to the argument augmented.
        index = row

        # Iterate over the rows above the substitution_row
        for j in range(row): 

            # Get the row to be reduced. The indexing here is similar as above, with the row variable replaced by the j variable.
            row_to_reduce = M[j,:]

            # Get the value of the element at the found index in the row to reduce
            value = row_to_reduce[index]
            
            # Perform the back substitution step using the formula row_to_reduce -> row_to_reduce - value * substitution_row
            row_to_reduce = row_to_reduce - value * substitution_row

            # Replace the updated row in the matrix, be careful with indexing!
            M[j,:] = row_to_reduce

    ### END CODE HERE ####

     # Extract the solution from the last column
    solution = M[:,-1]
    
    return solution

In [27]:
def gaussian_elimination(A, B):
    """
    Solve a linear system represented by an augmented matrix using the Gaussian elimination method.

    Parameters:
    - A (numpy.array): Square matrix of size n x n representing the coefficients of the linear system
    - B (numpy.array): Column matrix of size 1 x n representing the constant terms.

    Returns:
    numpy.array: The solution vector.
    """

    ### START CODE HERE ###

    # Get the matrix in row echelon form
    row_echelon_M = row_echelon_form(A, B)

    # Since the system is non-singular (by our assumptions), then perform back substitution to get the result. 
    solution = back_substitution(row_echelon_M)

    ### END SOLUTION HERE ###

    return solution
        