In [1]:
import numpy as np

Matrix Multiplication

In [3]:
A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print(f"Matrix A (3 x 3): \n {A}")

print("\n")

B = np.array([[2, 2], [5, 7], [4, 4]])
print(f"Matrix A (3 x 2): \n {B}")

Matrix A (3 x 3): 
 [[4 9 9]
 [9 1 6]
 [9 2 3]]


Matrix A (3 x 2): 
 [[2 2]
 [5 7]
 [4 4]]


using np.matmul() to multiply the two matrices

In [4]:
AxB = np.matmul(A,B)
print(AxB)

[[ 89 107]
 [ 47  49]
 [ 40  44]]


The python operator @ will also work 

In [5]:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

### Note:
        For matrix multiplication, the number of columns on the first matrix must be equal to the number of rows on the second matrix

In [6]:
try:
    np.matmul(B, A)
except Exception as e:
    print(e)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [7]:
try:
    B @ A
except Exception as e:
    print(e)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [8]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])

print("Shape of vector x:", x.shape)
print("Number of dimensions of vector x:", x.ndim)
print("Shape of vector x, reshaped to a matrix:", x.reshape((3, 1)).shape)
print("Number of dimensions of vector x, reshaped to a matrix:", x.reshape((3, 1)).ndim)

Shape of vector x: (3,)
Number of dimensions of vector x: 1
Shape of vector x, reshaped to a matrix: (3, 1)
Number of dimensions of vector x, reshaped to a matrix: 2


In [9]:
np.matmul(x, y)

np.int64(3)

### Note:
        np.dot() also works for matrix multiplication. What actually happens is called **Broadcasting** in python. Numpy broadcasts the dot product operation to all rows and columns, and you get the resultant product matrix. Broadcasting also works in other operations (+, -, etc)

In [10]:
np.dot(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

### LINEAR TRANSFORMATIONS

In [15]:
%pip install opencv-python

   ---------------------------------------- 0.0/39.5 MB ? eta -:--:--
    --------------------------------------- 0.5/39.5 MB 4.2 MB/s eta 0:00:10
   - -------------------------------------- 1.3/39.5 MB 3.7 MB/s eta 0:00:11
   -- ------------------------------------- 2.1/39.5 MB 3.7 MB/s eta 0:00:11
   -- ------------------------------------- 2.9/39.5 MB 3.6 MB/s eta 0:00:11
   --- ------------------------------------ 3.7/39.5 MB 3.6 MB/s eta 0:00:11
   ---- ----------------------------------- 4.5/39.5 MB 3.6 MB/s eta 0:00:10
   ----- ---------------------------------- 5.0/39.5 MB 3.6 MB/s eta 0:00:10
   ----- ---------------------------------- 5.8/39.5 MB 3.6 MB/s eta 0:00:10
   ------ --------------------------------- 6.6/39.5 MB 3.6 MB/s eta 0:00:10
   ------- -------------------------------- 7.3/39.5 MB 3.6 MB/s eta 0:00:10
   ------- -------------------------------- 7.9/39.5 MB 3.6 MB/s eta 0:00:09
   -------- ------------------------------- 8.7/39.5 MB 3.6 MB/s eta 0:00:09
   ---

In [16]:
import cv2

In [17]:
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [18]:
def T(v):
    w = np.zeros((3, 1))
    w[0,0] = 3*v[0,0]
    w[2,0] = -2*v[1,0]
    
    return w

v = np.array([[3], [5]])
w = T(v)

print("Original vector:\n", v, "\n\n Result of the transformation:\n", w)

Original vector:
 [[3]
 [5]] 

 Result of the transformation:
 [[  9.]
 [  0.]
 [-10.]]


A transformation  𝑇
  is said to be linear if the following two properties are true for any scalar  𝑘
 , and any input vectors  𝑢
  and  𝑣
 :

    𝑇(𝑘𝑣)=𝑘𝑇(𝑣)
 
    𝑇(𝑢+𝑣)=𝑇(𝑢)+𝑇(𝑣)


In [20]:
u = np.array([[1], [-2]])
v = np.array([[2], [4]])

k = 7

print(f"T(kv): \n {T(k*v)}, \n k*T(v): \n {k*T(v)}")
print('\n')
print(f"T(u+v): \n {T(u + v)} \n T(u) + T(v): \n {T(u) + T(v)}")

T(kv): 
 [[ 42.]
 [  0.]
 [-56.]], 
 k*T(v): 
 [[ 42.]
 [  0.]
 [-56.]]


T(u+v): 
 [[ 9.]
 [ 0.]
 [-4.]] 
 T(u) + T(v): 
 [[ 9.]
 [ 0.]
 [-4.]]


In [22]:
def L(v):
    A = np.array([[3,0], [0,0], [0,-2]])
    print(f"Transformation of matrix: \n {A} \n")
    w = A @ v

    return w

v = np.array([[3], [5]])
w = L(v)

print(f"Original vector: \n {v}, \n\n Result of the transformation: \n {w}")

Transformation of matrix: 
 [[ 3  0]
 [ 0  0]
 [ 0 -2]] 

Original vector: 
 [[3]
 [5]], 

 Result of the transformation: 
 [[  9]
 [  0]
 [-10]]
